#声明端口
server:
  port: 8082

spring:
  application:
    #声明项目名称
    name: springcloud-ribbon


#声明向服务器注册地址
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.31.48:8082
    ip-address: 192.168.31.48 #可访问的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

logging:
  level:
    com.xphsc.easyjdbc: debug